version: '3.8'

services:
  postgres:
    image: 'postgres:16.6'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/soundclown
    ports:
      - "5400:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/soundclown

volumes:
  postgres_data:

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: soundclown_app
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/soundclown
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#    networks:
#      - soundclown-net

networks:
  soundclown-net:
