version: '3.8'

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: soundclown_minio
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
      MINIO_SERVER_URL: http://localhost:9000
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - minio_network

  # Create buckets and users on startup
  createbuckets:
    image: quay.io/minio/mc
    container_name: soundclown_minio_createbuckets
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10 &&
      mc alias set myminio http://minio:9000 minioadmin minioadmin &&
      mc mb --ignore-existing myminio/soundclown-audio &&
      mc mb --ignore-existing myminio/soundclown-artists-images &&
      mc mb --ignore-existing myminio/soundclown-albums-covers &&
      exit 0;
      "
    networks:
      - minio_network

volumes:
  minio_data:
    name: soundclown_minio_data

networks:
  minio_network:
    name: soundclown_minio_network
    driver: bridge 